# Generated by Django 3.2 on 2024-02-20 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный Email')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Отдел')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, verbose_name='Мобильный телефон')),
                ('internal_phone', models.CharField(blank=True, max_length=20, verbose_name='Внутренний телефон')),
                ('is_created', models.BooleanField(default=True, verbose_name='Запись создана')),
                ('is_updated', models.BooleanField(default=False, verbose_name='Запись обновлена')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Запись удалена')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
