# Generated by Django 3.2 on 2024-02-16 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20240215_1634'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='accounts_pr_user_id_20decd_idx',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='country',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='responsibilities',
        ),
        migrations.AddField(
            model_name='profile',
            name='chinese',
            field=models.CharField(blank=True, choices=[('1', 'Понимаю и разговариваю без проблем'), ('2', 'Если что-то не понимаю, то переспрашиваю'), ('3', 'Понимаю многое, но плохо говорю'), ('4', 'Понимаю немного, когда говорят очень медленно, но плохо говорю'), ('5', 'Не разговариваю совсем')], default='', max_length=30, verbose_name='Знание китайского языка'),
        ),
        migrations.AddField(
            model_name='profile',
            name='chinese_level',
            field=models.CharField(blank=True, choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1')], default='', max_length=40, verbose_name='Уровень знания китайского'),
        ),
        migrations.AddField(
            model_name='profile',
            name='english_level',
            field=models.CharField(blank=True, choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1')], default='', max_length=40, verbose_name='Уровень знания английского'),
        ),
        migrations.AddField(
            model_name='profile',
            name='german_level',
            field=models.CharField(blank=True, choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1')], default='', max_length=40, verbose_name='Уровень знания немецкого'),
        ),
        migrations.AddField(
            model_name='profile',
            name='russian_level',
            field=models.CharField(blank=True, choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1')], default='', max_length=40, verbose_name='Уровень знания русского'),
        ),
        migrations.AddField(
            model_name='profile',
            name='turkish',
            field=models.CharField(blank=True, choices=[('1', 'Понимаю и разговариваю без проблем'), ('2', 'Если что-то не понимаю, то переспрашиваю'), ('3', 'Понимаю многое, но плохо говорю'), ('4', 'Понимаю немного, когда говорят очень медленно, но плохо говорю'), ('5', 'Не разговариваю совсем')], default='', max_length=30, verbose_name='Знание турецкого языка'),
        ),
        migrations.AddField(
            model_name='profile',
            name='turkish_level',
            field=models.CharField(blank=True, choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1')], default='', max_length=40, verbose_name='Уровень знания турецкого'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='achievements_de',
            field=models.TextField(blank=True, verbose_name='Достижения и успехи (на немецком)'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='achievements_en',
            field=models.TextField(blank=True, verbose_name='Достижения и успехи (на латинице)'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='achievements_ru',
            field=models.TextField(blank=True, verbose_name='Достижения и успехи (на кириллице)'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='description_de',
            field=models.TextField(blank=True, verbose_name='Описание (на немецком)'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (на латинице)'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание (на кириллице)'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='location_city_de',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город работы (на немецком)'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='location_city_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город работы (на латинице)'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='location_city_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город работы (на кириллице)'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='location_country_de',
            field=models.CharField(blank=True, max_length=255, verbose_name='Страна работы (на немецком)'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='location_country_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Страна работы (на латинице)'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='location_country_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Страна работы (на кириллице)'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='salary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заработная плата'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='english',
            field=models.CharField(blank=True, choices=[('1', 'Понимаю и разговариваю без проблем'), ('2', 'Если что-то не понимаю, то переспрашиваю'), ('3', 'Понимаю многое, но плохо говорю'), ('4', 'Понимаю немного, когда говорят очень медленно, но плохо говорю'), ('5', 'Не разговариваю совсем')], default='', max_length=30, verbose_name='Знание английского языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='german',
            field=models.CharField(blank=True, choices=[('1', 'Понимаю и разговариваю без проблем'), ('2', 'Если что-то не понимаю, то переспрашиваю'), ('3', 'Понимаю многое, но плохо говорю'), ('4', 'Понимаю немного, когда говорят очень медленно, но плохо говорю'), ('5', 'Не разговариваю совсем')], default='', max_length=30, verbose_name='Знание немецкого языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='russian',
            field=models.CharField(blank=True, choices=[('1', 'Понимаю и разговариваю без проблем'), ('2', 'Если что-то не понимаю, то переспрашиваю'), ('3', 'Понимаю многое, но плохо говорю'), ('4', 'Понимаю немного, когда говорят очень медленно, но плохо говорю'), ('5', 'Не разговариваю совсем')], default='', max_length=30, verbose_name='Знание русского языка'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название компания'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания работы'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='accounts.profile', verbose_name='Профиль'),
        ),
    ]
