# Generated by Django 3.2 on 2024-02-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240216_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('is_employer', 'Работодатель'), ('is_student', 'Соискатель')], max_length=50, null=True, verbose_name='Роль'),
        ),
    ]
