# Generated by Django 3.2 on 2024-02-15 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('name', models.CharField(max_length=255, verbose_name='Название филлиала')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Текстовый адрес')),
                ('link_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка на адрес')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание как добраться')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_name', models.CharField(choices=[('Baden-Württemberg', 'Baden-Württemberg'), ('Bavaria', 'Bavaria'), ('Berlin', 'Berlin'), ('Brandenburg', 'Brandenburg'), ('Bremen', 'Bremen'), ('Hamburg', 'Hamburg'), ('Hesse', 'Hesse'), ('Lower Saxony', 'Lower Saxony'), ('Mecklenburg-Vorpommern', 'Mecklenburg-Vorpommern'), ('North Rhine-Westphalia', 'North Rhine-Westphalia'), ('Rhineland-Palatinate', 'Rhineland-Palatinate'), ('Saarland', 'Saarland'), ('Saxony', 'Saxony'), ('Saxony-Anhalt', 'Saxony-Anhalt'), ('Schleswig-Holstein', 'Schleswig-Holstein'), ('Thuringia', 'Thuringia')], max_length=100)),
            ],
            options={
                'verbose_name': 'Федеральная земля Германии',
                'verbose_name_plural': 'Федеральные земли Германии',
            },
        ),
        migrations.CreateModel(
            name='EmployerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('icon', models.ImageField(blank=True, upload_to='company_icons/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('iin', models.CharField(max_length=50, verbose_name='ИИН/БИН')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'Работодатель',
                'verbose_name_plural': 'Работодатели',
            },
        ),
        migrations.CreateModel(
            name='PositionEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название позиции')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'Позиция работника',
                'verbose_name_plural': 'Позиция работников',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.TextField(verbose_name='Обязанности')),
                ('experience', models.TextField(verbose_name='Опыт работы')),
                ('clothingform', models.CharField(max_length=255, verbose_name='Форма одежды')),
                ('employee_count', models.PositiveIntegerField(default=1, verbose_name='Количество работников')),
                ('employee_count_hired', models.PositiveIntegerField(default=0, verbose_name='Количество нанятых работников')),
                ('gender', models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский'), ('Any', 'Неважно')], max_length=50, verbose_name='Пол')),
                ('time_start', models.TimeField(verbose_name='Время начала работы')),
                ('time_end', models.TimeField(verbose_name='Время окончания работы')),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата')),
                ('description', models.TextField(blank=True, default='', verbose_name='Коментарий')),
                ('views_vacancy', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('increase_choices', models.BooleanField(default=False, verbose_name='Повышение зарплаты')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('language_german', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=50, null=True, verbose_name='Знание немецкого языка')),
                ('language_english', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=50, null=True, verbose_name='Знание английского языка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='Филиал')),
                ('employer_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Работодатель')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.positionemployee', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='ReviewBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, default='', verbose_name='Отзыв')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='Филиал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв филиала',
                'verbose_name_plural': 'Отзывы филиалов',
            },
        ),
        migrations.CreateModel(
            name='RatingEmployerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Рейтинг')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Компания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рейтинг компании',
                'verbose_name_plural': 'Рейтинги компаний',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='Отклонено')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Принято')),
                ('is_work', models.BooleanField(default=False, verbose_name='Работает')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Работодатель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Приглашение на вакансию',
                'verbose_name_plural': 'Приглашения на вакансии',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_land_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Федеральная земля в Германии'),
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Компания'),
        ),
    ]
