# Generated by Django 3.2 on 2024-02-15 10:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20240215_1634'),
        ('core', '0004_auto_20240103_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='Отклонено')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Принято')),
                ('is_work', models.BooleanField(default=False, verbose_name='Работает')),
            ],
            options={
                'verbose_name': 'Приглашение на вакансию',
                'verbose_name_plural': 'Приглашения на вакансии',
            },
        ),
        migrations.RemoveField(
            model_name='clothingform',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='dutyemployee',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_increase',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 15, 10, 34, 53, 499035, tzinfo=utc), verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employee_count_hired',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество нанятых работников'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='increase_choices',
            field=models.BooleanField(default=False, verbose_name='Повышение зарплаты'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='language_english',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=50, null=True, verbose_name='Знание английского языка'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='language_german',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=50, null=True, verbose_name='Знание немецкого языка'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='clothingform',
            field=models.CharField(max_length=255, verbose_name='Форма одежды'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='duty',
            field=models.TextField(verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='gender',
            field=models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский'), ('Any', 'Неважно')], max_length=50, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.positionemployee', verbose_name='Позиция'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['city'], name='core_branch_city_id_97ceff_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['company'], name='core_branch_company_9dd70f_idx'),
        ),
        migrations.AddIndex(
            model_name='employercompany',
            index=models.Index(fields=['user'], name='core_employ_user_id_bc9c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='positionemployee',
            index=models.Index(fields=['employer'], name='core_positi_employe_a49f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewbranch',
            index=models.Index(fields=['branch'], name='core_review_branch__bcbb89_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewbranch',
            index=models.Index(fields=['user'], name='core_review_user_id_2e241b_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['employer_company'], name='core_vacanc_employe_84c983_idx'),
        ),
        migrations.DeleteModel(
            name='ClothingForm',
        ),
        migrations.DeleteModel(
            name='DutyEmployee',
        ),
        migrations.AddField(
            model_name='invitation',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Работодатель'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['employer'], name='core_invita_employe_6efbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['vacancy'], name='core_invita_vacancy_42e1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['user'], name='core_invita_user_id_aaba7e_idx'),
        ),
    ]
